### ISSUE TITLE
Bug: /work displays "You've already worked in the last 30 minutes." but the limit is 5 minutes

### ISSUE THREAD

**Issue by CyntexMore** [vb2007/discordbot#33]
The title basically.

**Comment by CyntexMore** [comment]
![nigmany](https://github.com/user-attachments/assets/8017543e-4c5d-4400-bbbb-3ae4fa6061e7)

I was told to attach this :3

**Comment by vb2007** [comment]
Fixed with the following commit:
https://github.com/vb2007/discordbot/commit/ae81dc67be6e0d1bf1b99f5ee2f0bc8453302b47
