### ISSUE TITLE
Bug: Economy cooldowns reset even if a request fails.

### ISSUE THREAD

**Issue by pml68** [vb2007/discordbot#40]
I run /rob, the application doesn't respond, then I run it again immediately after and the cooldown's at 30 minutes again
![image](https://github.com/user-attachments/assets/f5995f43-e827-490b-ba11-5b33cf75f385)

**Comment by vb2007** [comment]
Update: The bot in fact executes the interaction, but just fails to reply.

If the `lastWorkTime`, `lastRobTime`, etc. columns get updated, that means the balance gets added to the user's economy record as well.

**Comment by vb2007** [comment]
The reset is related to the fact that the bot can't handle the interaction request under 3 seconds.

So the Discord API returns an error, but the interaction gets executed on the bot's side.

Tracking on: https://github.com/vb2007/discordbot/issues/93
